language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- npm test
after_success:
- ember build
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
env:
  global:
  - secure: e25iIdehr1eZ1mtyeJdNFXBcl40HkT626ZR8LnGF/1LmfYYWByj4ebcHPDM73ITwlcCZ+g/3fF+FOudPcoIgLAppX+mnAo5LzBVqHsHPnwR6FHk0DNuwza84v+j1P/LR09T5ywo01ukd79RFdPaVUr44Ixioh2grz6ecS6IaOa4=
  - secure: Jh1bo9wjpqp5RvJy1IoaMmNj1dhgb3mNfoZTBvtXJ+Q6UoRZkdtNjuJkUZPMPM2wi0JM9pdW3sHsGQn0n2FN+ajgxr1A/nmC4xZJIx9qOyHmyYCLF/4tmDbxG1082P8m+MzIlGRiFIVj9MfDC6glejlQCT6I7cFdk132b2XUChA=
